"""Database tables for DispatchLedger.

Every business table carries a tenant_id, so each distributor company's data
can be isolated with Postgres row-level security.
"""

import uuid
from datetime import date, datetime
from decimal import Decimal

from sqlalchemy import (
    CheckConstraint,
    Date,
    DateTime,
    ForeignKey,
    Integer,
    Numeric,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    pass


# ---------- Shared column groups ----------

class IdMixin:
    """UUID primary key generated by Postgres."""

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )


class TimestampMixin:
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


class TenantScopedMixin(IdMixin, TimestampMixin):
    """Every business table belongs to exactly one tenant."""

    tenant_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("tenants.id", ondelete="CASCADE"), index=True
    )


# ---------- Tables ----------

class Tenant(IdMixin, TimestampMixin, Base):
    """A fuel distributor company using the platform."""

    __tablename__ = "tenants"

    name: Mapped[str] = mapped_column(String(200))
    slug: Mapped[str] = mapped_column(String(100), unique=True)


class User(TenantScopedMixin, Base):
    """A person who logs in: admin, dispatcher, or driver."""

    __tablename__ = "users"
    __table_args__ = (
        # Email is unique within a tenant, not globally: the same person may
        # work for two distributors that both use the platform.
        UniqueConstraint("tenant_id", "email", name="uq_users_tenant_email"),
        CheckConstraint("role IN ('admin', 'dispatcher', 'driver')", name="ck_users_role"),
    )

    email: Mapped[str] = mapped_column(String(255))
    full_name: Mapped[str] = mapped_column(String(200))
    role: Mapped[str] = mapped_column(String(20))
    password_hash: Mapped[str] = mapped_column(Text)


class Customer(TenantScopedMixin, Base):
    """A business the distributor sells fuel to."""

    __tablename__ = "customers"
    __table_args__ = (
        CheckConstraint("payment_terms_days >= 0", name="ck_customers_terms"),
    )

    name: Mapped[str] = mapped_column(String(200))
    email: Mapped[str | None] = mapped_column(String(255))
    phone: Mapped[str | None] = mapped_column(String(50))
    payment_terms_days: Mapped[int] = mapped_column(Integer, server_default="30")


class DeliverySite(TenantScopedMixin, Base):
    """A tank at one of a customer's locations."""

    __tablename__ = "delivery_sites"
    __table_args__ = (
        CheckConstraint("tank_capacity_gal > 0", name="ck_sites_capacity"),
    )

    customer_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("customers.id", ondelete="CASCADE"), index=True
    )
    address: Mapped[str] = mapped_column(Text)
    tank_capacity_gal: Mapped[Decimal] = mapped_column(Numeric(10, 2))


class Product(TenantScopedMixin, Base):
    """A fuel product such as diesel, gasoline, or DEF."""

    __tablename__ = "products"
    __table_args__ = (
        UniqueConstraint("tenant_id", "name", name="uq_products_tenant_name"),
        CheckConstraint("current_price >= 0", name="ck_products_price"),
    )

    name: Mapped[str] = mapped_column(String(100))
    unit: Mapped[str] = mapped_column(String(20), server_default="gal")
    current_price: Mapped[Decimal] = mapped_column(Numeric(12, 4))


class Order(TenantScopedMixin, Base):
    """A customer's request for fuel. unit_price is a snapshot at order time."""

    __tablename__ = "orders"
    __table_args__ = (
        CheckConstraint(
            "status IN ('pending', 'scheduled', 'delivered', 'cancelled')",
            name="ck_orders_status",
        ),
        CheckConstraint("quantity_gal > 0", name="ck_orders_quantity"),
    )

    customer_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("customers.id"), index=True)
    site_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("delivery_sites.id"), index=True)
    product_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("products.id"), index=True)
    quantity_gal: Mapped[Decimal] = mapped_column(Numeric(10, 2))
    unit_price: Mapped[Decimal] = mapped_column(Numeric(12, 4))
    status: Mapped[str] = mapped_column(String(20), server_default="pending")
    requested_date: Mapped[date] = mapped_column(Date)


class Delivery(TenantScopedMixin, Base):
    """The truck actually showing up. delivered_gal can differ from the order."""

    __tablename__ = "deliveries"
    __table_args__ = (
        CheckConstraint(
            "status IN ('scheduled', 'in_transit', 'completed', 'failed')",
            name="ck_deliveries_status",
        ),
        CheckConstraint("delivered_gal IS NULL OR delivered_gal >= 0", name="ck_deliveries_gal"),
    )

    order_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("orders.id"), index=True)
    driver_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("users.id"), index=True)
    scheduled_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    delivered_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    delivered_gal: Mapped[Decimal | None] = mapped_column(Numeric(10, 2))
    status: Mapped[str] = mapped_column(String(20), server_default="scheduled")


class Invoice(TenantScopedMixin, Base):
    """Billing for what was actually delivered."""

    __tablename__ = "invoices"
    __table_args__ = (
        UniqueConstraint("tenant_id", "invoice_number", name="uq_invoices_tenant_number"),
        CheckConstraint("status IN ('unpaid', 'paid', 'void')", name="ck_invoices_status"),
        CheckConstraint("amount >= 0", name="ck_invoices_amount"),
    )

    customer_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("customers.id"), index=True)
    delivery_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("deliveries.id"), unique=True
    )
    invoice_number: Mapped[str] = mapped_column(String(50))
    issued_at: Mapped[date] = mapped_column(Date)
    due_date: Mapped[date] = mapped_column(Date)
    amount: Mapped[Decimal] = mapped_column(Numeric(12, 2))
    status: Mapped[str] = mapped_column(String(20), server_default="unpaid")
    paid_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
